language: java

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
      sudo: false
    - os: osx
      osx_image: xcode7.3

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update        ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then /usr/libexec/java_home -V; fi

install:
  - git clone -n https://github.com/ClearVolume/scenery.git --depth 1
  - cd scenery/
  - git checkout HEAD jars/openvr-0.1.jar
  - cd ..

script:
  - mvn initialize
  - mvn compile
    
#after_success:
#    - gradle uploadArchives -Plocal=true
