language: java

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
      sudo: false
    - os: osx
      osx_image: xcode7.3

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update        ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then /usr/libexec/java_home -V; fi

script:
  - mvn jar  
    
#after_success:
#    - gradle uploadArchives -Plocal=true
